-- Criação da tabela de Ativos para Monitoramento
CREATE TABLE IF NOT EXISTS assets (
    ticker VARCHAR(10) PRIMARY KEY,
    name VARCHAR(255),
    sector VARCHAR(100),
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela para armazenar os sinais detectados (HiLo Flip)
CREATE TABLE IF NOT EXISTS signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(10) REFERENCES assets(ticker),
    signal_date DATE NOT NULL,
    direction VARCHAR(4) CHECK (direction IN ('BUY', 'SELL')), -- BUY = Cruzou pra cima (Call), SELL = Cruzou pra baixo (Put)
    price_at_signal DECIMAL(10, 2),
    hilo_value DECIMAL(10, 2),
    processed BOOLEAN DEFAULT FALSE, -- Se já buscamos opções para esse sinal
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela para sugerir opções baseadas nos sinais
CREATE TABLE IF NOT EXISTS option_opportunities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT REFERENCES signals(id),
    ticker_asset VARCHAR(10),
    ticker_option VARCHAR(20),
    option_type VARCHAR(4) CHECK (option_type IN ('CALL', 'PUT')),
    strike DECIMAL(10, 2),
    expiration_date DATE,
    premium_at_signal DECIMAL(10, 2),
    distance_to_strike DECIMAL(5, 2), -- % de distância do preço atual
    days_to_expire INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indices para performance
CREATE INDEX IF NOT EXISTS idx_signals_date ON signals(signal_date);
CREATE INDEX IF NOT EXISTS idx_signals_ticker ON signals(ticker);

-- Seed inicial de ativos (Opcional, mas útil)
INSERT INTO assets (ticker, name, active) VALUES
('PETR4', 'Petrobras PN', TRUE),
('VALE3', 'Vale ON', TRUE),
('BOVA11', 'ETF Ibovespa', TRUE)
ON CONFLICT (ticker) DO NOTHING;
